# Orange Fox specific settings
OF_MAINTAINER := Aifinef
OF_SCREEN_H := 2400
OF_STATUS_H := 100
OF_HIDE_NOTCH := true
OF_CLOCK_POS := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_KEEP_DM_VERITY := 1
