# OrangeFox specific settings for RMX3636
FOX_VIRTUAL_AB_DEVICE := 1
FOX_AB_DEVICE := 1
OF_DEFAULT_KEYMASTER_VERSION := 4.1
FOX_USE_SPECIFIC_MAGISK_ZIP := 1
OF_USE_MAGISKBOOT := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_KEEP_DM_VERITY := 1
OF_USE_LZMA_COMPRESSION := 1
